# Generated by Django 5.0.6 on 2024-07-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctormodel',
            name='available_time',
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='available_time',
            field=models.ManyToManyField(to='doctor.availabletime'),
        ),
    ]
